FROM openjdk:11
WORKDIR /app
COPY ./backend .
RUN apt-get update && apt-get install -y maven
RUN mvn clean install
EXPOSE 8080
CMD ["java", "-Xss8m", "-Dcom.sun.jndi.ldap.object.trustURLCodebase=true", "-jar", "target/springboot-app-0.0.1-SNAPSHOT.jar"]